services:
  - type: web
    name: rigelstok-server
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.9.18"
    healthCheckPath: /health
    disk:
      name: rigelstok-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1